# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59270f100fd5f043cabf53bdf985a4f22c297568c64848af9b9739c1f02773682f3489694fcea28460c0616d09ebbf3825255395cd1d3928dfeab4da6d3d7bd8

test:
  secret_key_base: dc74abd07974cd86ca4a0a63a2725756968445eeebb42f68b162e2f923b7e27d7f6616ce65ac54d6a1dc9da5760639a821eceef8c97f1de9eccb68829bc8dc49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
